const CardMangaData = [
    {
        //img : Through_My_Window,
        title : "Ao Ashi",
        Author :	"Yuugo Kobayashi - Naohiko Ueno",
        Status :	"Ongoing",
        Genres :	"School life - Seinen - Sports",
     },
     {
        //img : Through_My_Window,
        title : "Apotheosis",
        Author :	"Ranzai Studio",
        Status :	"Ongoing",
        Genres :	"Action - Fantasy - Martial arts - Shounen",
     },
    {
        //img : Through_My_Window,
        title : "Tales Of Demons And Gods",
        Author :	"Mad Snail",
        Status :	"Ongoing",
        Genres :	"Action - Adventure - Comedy - Drama - Fantasy - Harem - Romance - Shounen - Manhua",
    },
    {
        //img : Through_My_Window,
        title : "One Piece",
        Author :    "Oda Eiichiro",
        Status :	"Ongoing",
        Genres :	"Action - Adventure - Comedy - Drama - Fantasy - Shounen",
    },
    {
        //img : Through_My_Window,
        title : "Solo Leveling",
        Author :	"Sung-Lak Jang",
        Status :	"Ongoing",
        Genres :	"Action - Adventure - Fantasy - Shounen - Webtoons",
    },
    {
        //img : Through_My_Window,
        title : "The Beginning After The End",
        Author :	"Turtleme - Fuyuki23",
        Status :	"Ongoing",
        Genres :	"Action - Adventure - Comedy - Fantasy - Webtoons",
    },
    {
        //img : Through_My_Window,
        title : "Kimetsu No Yaiba",
        Author :	"Gotouge Koyoharu",
        Status :	"Finished",
        Genres :	"Adventure - Fantasy - Historical - Shounen",
    },
    {
        //img : Through_My_Window,
        title : "Black Clover",
        Author :	"Tabata Yuuki",
        Status :	"Ongoing",
        Genres :	"Action - Comedy - Fantasy - Sci fi - Shounen - Supernatural",
    },
    {
        //img : Through_My_Window,
        title : "Mercenary Enrollment",
        Author :	"Yc",
        Status :	"Ongoing",
        Genres :	"Action - Adventure - Drama - Romance - Sci fi",
    },
    {
        //img : Through_My_Window,
        title : "Nano Machine",
        Author :	"Great H (현절무) - Hanjung Wolya (한중월야)",
        Status :	"Ongoing",
        Genres :	"Action - Adventure - Fantasy - Martial arts",
    },
    {
        //img : Through_My_Window,
        title : "Nanatsu No Taizai",
        Author :	"Suzuki Nakaba",
        Status :	"Ongoing",
        Genres :	"Action - Adventure - Comedy - Drama - Fantasy - Shounen - Supernatural",
    },
    {
        //img : Through_My_Window,
        title : "Medical Return",
        Author :	"Kidari Studio - Yuin - Yeon Jae Joong",
        Status :	"Finished",
        Genres :	"Action - Comedy - Fantasy - Webtoons",
    },
    {
        //img : Through_My_Window,
        title : "The Tutorial Tower's Advanced Player",
        Author :	"방구석김씨 - 오마감",
        Status :	"Ongoing",
        Genres :	"Action - Adventure - Fantasy",
    },
    {
        //img : Through_My_Window,
        title : "The Player That Can't Level Up",
        Author :	"Gavinge - Parrot Kim - Park Jungjae - Parrot Kim - Studio Khit",
        Status :	"Ongoing",
        Genres :	"Action - Adventure - Fantasy - Mystery - Manhwa",
    },
    {
        //img : Through_My_Window,
        title : "Murim Login",
        Author :	"원작 제로빅",
        Status :	"Ongoing",
        Genres :	"Action",
    },
    {
        //img : Through_My_Window,
        title : "",
        Author :	"",
        Status :	"",
        Genres :	"",
    },

];
export default CardMangaData;