const CardAnimeData = [
    {
        //img : Through_My_Window,
        title : "One Piece",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Hunter x Hunter",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Haikyuu",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Haikyuu: Second Season",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Haikyuu: Karasuno Koukou vs. Shiratorizawa Gakuen Koukou",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Haikyuu: To the Top",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Haikyuu: To the Top Part 2",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Kuroko no Basket",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Kuroko no Basket 2nd Season",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Kuroko no Basket 3rd Season",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Ballroom e Youkoso",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Slam Dunk",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Metal Fight Beyblade",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Captain Tsubasa",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "Inazuma Eleven Go",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
    {
        //img : Through_My_Window,
        title : "",
        Status :	"",
        Genres :	"",
        Studio : "",
    },
];
export default CardAnimeData;
