import Through_My_Window from "../assets/Through_My_Window.webp"
import the_A_team from "../assets/the_A_team.jpg"
const CardMovieData = [
    {
        img : Through_My_Window,
        title : "Trough my window",
        Released_Year : "2022",
        duration : "1h 56m",
     },
     {
        img : the_A_team,
        title : "The A team",
        Released_Year : "2010",
        duration : "1h 57m",
     },
     {
        img : the_A_team,
        title : "Purple Hearts",
        Released_Year : "2022",
        duration : "2h 2m",
     },
     {
        img : the_A_team,
        title : "2012",
        Released_Year : "2009",
        duration : "2h 38m",
     },
     {
        img : the_A_team,
        title : "Bee",
        Released_Year : "2007",
        duration : "1h 31m",
     },
     {
        img : the_A_team,
        title : "Ted",
        Released_Year : "2012",
        duration : "1h 46m",
     },
     {
        img : the_A_team,
        title : "Ted 2",
        Released_Year : "2015",
        duration : "1h 55m",
     },
     {
        img : the_A_team,
        title : "21 Jump Street",
        Released_Year : "2012",
        duration : "1h 49m",
     },
     {
        img : the_A_team,
        title : "22 Jump Street",
        Released_Year : "2014",
        duration : "1h 52m",
     },
     {
        img : the_A_team,
        title : "Friends with Benefits",
        Released_Year : "2011",
        duration : "1h 49m",
     },
     {
        img : the_A_team,
        title : "No Strings Attached",
        Released_Year : "2011",
        duration : "1h 48m",
     },
     {
        img : the_A_team,
        title : "Red",
        Released_Year : "2010",
        duration : "1h 51m",
     },
     {
        img : the_A_team,
        title : "Red 2",
        Released_Year : "2013",
        duration : "1h 56m",
     },
     {
        img : the_A_team,
        title : "The Transporter",
        Released_Year : "2002",
        duration : "1h 32m",
     },
     {
        img : the_A_team,
        title : "Taken 2",
        Released_Year : "2012",
        duration : "1h 32m",
     },
     {
        img : the_A_team,
        title : "The Italian Job",
        Released_Year : "2003",
        duration : "1h 51m",
     },
     {
        img : the_A_team,
        title : "Olympus Has Fallen",
        Released_Year : "2013",
        duration : "1h 59m",
     },
     {
        img : the_A_team,
        title : "World War Z",
        Released_Year : "2013",
        duration : "1h 56m",
     },
     {
        img : the_A_team,
        title : "Training Day",
        Released_Year : "2001",
        duration : "2h 2m",
     },
     {
        img : the_A_team,
        title : "Wonder Woman",
        Released_Year : "2017",
        duration : "2h 21m",
     },
     {
        img : the_A_team,
        title : "Kung Fu Panda",
        Released_Year : "2008",
        duration : "1h 32m",
     },
     {
        img : the_A_team,
        title : "Shrek",
        Released_Year : "2001",
        duration : "1h 30m",
     },
     {
        img : the_A_team,
        title : "Shrek 2",
        Released_Year : "2004",
        duration : "1h 33m",
     },
     {
        img : the_A_team,
        title : "King Kong",
        Released_Year : "2005",
        duration : "3h 7m",
     },
     {
        img : the_A_team,
        title : "Despicable Me",
        Released_Year : "2010",
        duration : "1h 35m",
     },
     {
        img : the_A_team,
        title : "Madagascar",
        Released_Year : "2005",
        duration : "1h 26m",
     },
     {
        img : the_A_team,
        title : "Madagascar: Escape 2 Africa",
        Released_Year : "2008",
        duration : "1h 29m",
     },
     {
        img : the_A_team,
        title : "How to Train Your Dragon",
        Released_Year : "2010",
        duration : "1h 38m",
     },
     {
        img : the_A_team,
        title : "How to Train Your Dragon 2",
        Released_Year : "2014",
        duration : "1h 42m",
     },
];
export default CardMovieData;