import manifest from "../assets/manifest.jpg"
import sex_education from "../assets/sex_education.jpg"
import wednesday from "../assets/wednesday.jpg"
import breaking_bad from "../assets/breaking_bad.jpg"
import fate_the_winx_saga from "../assets/fate_the_winx_saga.jpg"
import alice_in_borderland from "../assets/alice_in_borderland.jpg"
import ginny_and_georgia from "../assets/ginny_and_georgia.jpg"
import you from "../assets/You.jpg"
import dark from "../assets/Dark.jpg"
import lucifer from "../assets/Lucifer.jpg"
import suits from "../assets/Suits.jpg"
import the_queens_gambit from "../assets/The_Queens_Gambit.jpeg"
import the_witcher from "../assets/The_witcher.jpg"
import game_of_thrones from "../assets/game_of_thrones.jpeg"
import the_imperfects from "../assets/the_imperfects.jpg"
import squid_game from "../assets/squid_game.jpg"
import locke_and_key from "../assets/locke_and_key.jpg"
const CardTvShowData = [
    {
        img : manifest,
        title : "Manifest",
        progress : "Finished", 
        max_season : "4 seasons",
        new_season : "2 Juin",
        progress_value : "100" ,
        creator : "Jeff Rake",
        storyline : "When Montego Air Flight 828 landed safely after a turbulent but routine flight, the crew and passengers were relieved. But in the span of those few hours, the world had aged five years - and their friends, families and colleagues, after mourning their loss, had given up hope and moved on. Now, faced with the impossible, they're all given a second chance. But as their new realities become clear, a deeper mystery unfolds and some of the returned passengers soon realize they may be meant for something greater than they ever thought possible.",
        Genres : "Drama - Mystery - Sci-Fi - Thriller",
        Release_date : "September 24, 2018 (United States)",
        Country_of_origin :  "United States",

      },
     {
        img : sex_education,
        title : "Sex education",
        progress : "Finished ", 
        max_season : "3 seasons",
        new_season : "MAYBE",
        progress_value : "100" ,
        storyline : "Socially awkward high school student Otis may not have much experience in the lovemaking department, but he gets good guidance on the topic in his personal sex ed course -- living with mom Jean, who is a sex therapist. Being surrounded by manuals, videos and tediously open conversations about sex, Otis has become a reluctant expert on the subject. When his classmates learn about his home life, Otis decides to use his insider knowledge to improve his status at school, so he teams with whip-smart bad girl Maeve to set up an underground sex therapy clinic to deal with their classmates' problems. But through his analysis of teenage sexuality, Otis realizes that he may need some therapy of his own.",
        Genres : "Comedy - Drama",
        Release_date : "January 11, 2019 (United States)",
        Country_of_origin :  "United Kingdom",
     },
     {
        img : wednesday,
        title : "Wednesday",
        progress : "Finished ", 
        max_season : "1 season",
        new_season : "MAYBE",
        progress_value : "100" ,
        storyline : "A sleuthing, supernaturally infused mystery charting Wednesday Addams' years as a student at Nevermore Academy. Wednesday's attempts to master her emerging psychic ability, thwart a monstrous killing spree that has terrorized the local town, and solve the supernatural mystery that embroiled her parents 25 years ago - all while navigating her new and very tangled relationships at Nevermore.",
        Genres : "Comedy - Crime - Fantasy - Mystery",
        Release_date : "November 23, 2022 (United States)",
        Country_of_origin :  "United States",
     },
     {
        img : breaking_bad,
        title : "Breaking bad",
        progress : "Finished ", 
        max_season : "5 seasons",
        new_season : "NOPE",
        progress_value : "100" ,
        storyline : "Walter H. White is a chemistry genius, but works as a chemistry teacher in an Albequerque, New Mexico high school. His life drastically changes when he's diagnosed with stage III terminal lung cancer, and given a short amount of time left to live: a mere matter of months. To ensure his handicapped son and his pregnant wife have a financial future, Walt uses his chemistry background to create and sell the world's finest crystal methamphetamine. To sell his signature 'blue meth,' he teams up with Jesse Pinkman, a former student of his. The meth makes them very rich very quickly, but it attracts the attention of his DEA brother in law Hank. As Walt and Jesse's status in the drug world escalates, Walt becomes a dangerous criminal and Jesse becomes a hot-headed salesman. Hank is always hot on his tail, and it forces Walt to come up with new ways to cover his tracks.",
        Genres : "CrimeDramaThriller",
        Release_date : "January 20, 2008 (United States)",
        Country_of_origin :  "United States",
     },
     {
        img : fate_the_winx_saga,
        title : "Fate the winx saga",
        progress : "Finished ", 
        max_season : "2 seasons",
        new_season : "MAYBE",
        progress_value : "100" ,
        storyline : "A live-action adaptation of Nickelodeon's Winx Club (2004). It follows Bloom as she adjusts to life in the Otherworld, where she must learn to control her dangerous magical powers.",
        Genres : "Action - Adventure - Drama - Fantasy",
        Release_date : "January 22, 2021 (United States)",
        Country_of_origin :  "Italy - United Kingdom",
     },
     {
        img : alice_in_borderland,
        title : "Alice in borderland",
        progress : "Finished ", 
        max_season : "2 seasons",
        new_season : "NOPE",
        progress_value : "100" ,
        storyline : "Arisu is a man without much money or luck. He is unemployed currently as well. Out of the blue a blinding light engulfs him one day in whose aftermath the city of Tokyo has lost all its inhabitants save Arisu and two friends. This is a dangerous and potentially fatal game of survival now in which they are forced to take part",
        Genres : "Action - Drama - Mystery - Sci-Fi - Thriller",
        Release_date : "December 10, 2020 (United States)",
        Country_of_origin :  "Japan",
     },
     {
        img : ginny_and_georgia,
        title : "Ginny & Georgia",
        progress : "S1 / EP4", 
        max_season : "2 seasons",
        new_season : "NOPE",
        progress_value : "30" ,
        storyline : "Angsty, awkward 15-year-old Ginny Miller often feels more mature than her 30-year-old mother, the irresistible, dynamic Georgia Miller. After years on the run, Georgia desperately wants to put down roots in picturesque New England and give her family something they've never had: a normal life. But it's not all carpool and Kombucha; Georgia's past threatens her and her family's new lifestyle, and Georgia will do anything to protect her family.",
        Genres : "Comedy - Drama",
        Release_date : "February 24, 2021 (United States)",
        Country_of_origin :  "United States",
     },
     {
        img : you,
        title : "You",
        progress : "S3", 
        max_season : "4 seasons",
        new_season : "Part 2 of 4th season",
        progress_value : "70" ,
        storyline : "Based on Caroline Kepnes' best-selling novel of the same name, YOU is a 21st century love story that asks, 'What would you do for love?' When a brilliant bookstore manager crosses paths with an aspiring writer, his answer becomes clear: anything. Using the internet and social media as his tools to gather the most intimate of details and get close to her, a charming and awkward crush quickly becomes obsession as he quietly and strategically removes every obstacle - and person - in his way.",
        Genres : "Crime - Drama - Romance - Thriller",
        Release_date : "September 9, 2018 (United States)",
        Country_of_origin :  "United States",
     },
     {
      img : dark,
      title : "Dark",
      progress : "Finished", 
      max_season : "3 seasons",
      new_season : "NOPE",
      progress_value : "100" ,
      storyline : "The first German production from the world's leading Internet TV Network is set in a present-day German town where the disappearance of two young children exposes the double lives and fractured relationships among four families. In 10 hour-long episodes, the story takes on a surprising twist that ties back to the same town in 1986.",
      Genres : "CrimeDramaMysterySci-FiThriller",
      Release_date : "December 1, 2017 (United States)",
      Country_of_origin :  "Germany - United States",
      },
      {
         img : lucifer,
         title : "Lucifer",
         progress : "Finished", 
         max_season : "6 seasons",
         new_season : "NOPE",
         progress_value : "100" ,
         storyline : "Lucifer Morningstar, bored from his sulking life in hell, comes to live in Los Angeles. While there, he helps humanity with its miseries through his experience and telepathic abilities to bring people's deepest desires and thoughts out of them. While meeting with a Detective in his nightclub (Lux), a shootout involving him and the Detective leads him to become an LAPD consultant who tries to punish people for their crimes through law and justice.",
         Genres : "Crime - Drama - Fantasy",
         Release_date : "January 25, 2016 (United States)",
         Country_of_origin :  "United States",
      },
      {
         img : suits,
         title : "Suites",
         progress : "Finished", 
         max_season : "9 seasons",
         new_season : "NOPE",
         progress_value : "100" ,
         storyline : "While running from a drug deal gone bad, brilliant young college-dropout Mike Ross slips into a job interview with one of New York City's best legal closers, Harvey Specter. Tired of cookie-cutter law school grads, Harvey takes a gamble by hiring Mike on the spot after recognizing his raw talent and photographic memory. Mike and Harvey are a winning team. Although Mike is a genius, he still has a lot to learn about the law; and while Harvey might seem like an emotionless, cold-blooded shark, Mike's sympathy and concern for their cases and clients will help remind Harvey why he went into law in the first place. Mike's other allies in the office include the firm's best paralegal Rachel and Harvey's no-nonsense assistant Donna. Proving to be an irrepressible duo and invaluable to the practice, Mike and Harvey must keep their secret from everyone including managing partner Jessica and Harvey's arch nemesis Louis, who seems intent on making Mike's life as difficult as possible.",
         Genres : " Comedy - Drama",
         Release_date : "June 23, 2011 (United States)",
         Country_of_origin :  "United States",
      },
      {
         img : the_queens_gambit,
         title : "The Queens Gambit",
         progress : "Finished", 
         max_season : "1 season",
         new_season : "MAYBE",
         progress_value : "100" ,
         storyline : "Nine year-old orphan Beth Harmon is quiet, sullen, and by all appearances unremarkable. That is, until she plays her first game of chess. Her senses grow sharper, her thinking clearer, and for the first time in her life she feels herself fully in control. By the age of sixteen, she's competing for the U.S. Open championship. But as Beth hones her skills on the professional circuit, the stakes get higher, her isolation grows more frightening, and the thought of escape becomes all the more tempting. Based on the book by Walter Tevis.",
         Genres : "Drama",
         Release_date : "October 23, 2020 (United States)",
         Country_of_origin :  "United States",
      },
      {
         img : the_witcher,
         title : "The witcher",
         progress : "Finished", 
         max_season : "2 seasons",
         new_season : "MAYBE",
         progress_value : "100" ,
         storyline : "The Witcher is a fantasy drama web television series created by Lauren Schmidt Hissrich for Netflix. It is based on the book series of the same name by Polish writer Andrzej Sapkowski. The Witcher follows the story of Geralt of Rivia, a solitary monster hunter, who struggles to find his place in a world where people often prove more wicked than monsters and beasts. But when destiny hurtles him toward a powerful sorceress, and a young princess with a special gift, the three must learn to navigate independently the increasingly volatile Continent.",
         Genres : "Action - Adventure - Drama - Fantasy - Mystery",
         Release_date : "December 20, 2019 (United States)",
         Country_of_origin :  "Poland - United States - Hungary",
      },
      {
         img : game_of_thrones,
         title : "Game Of Thrones",
         progress : "Finished", 
         max_season : "8 seasons",
         new_season : "NOPE",
         progress_value : "100" ,
         storyline : "In the mythical continent of Westeros, several powerful families fight for control of the Seven Kingdoms. As conflict erupts in the kingdoms of men, an ancient enemy rises once again to threaten them all. Meanwhile, the last heirs of a recently usurped dynasty plot to take back their homeland from across the Narrow Sea.",
         Genres : "Action - Adventure - Drama - Fantasy",
         Release_date : "April 17, 2011 (United States)",
         Country_of_origin :  "United States - United Kingdom",
      },
      {
         img : the_imperfects,
         title : "The Imperfects",
         progress : "Finished", 
         max_season : "1 season",
         new_season : "NOT YET",
         progress_value : "100" ,
         storyline : "The drama revolves around three twenty-somethings who, following an experimental gene therapy, are turned into monsters who band together to hunt down the scientist responsible and force him to make them human again. Dr. Sydney Burke, a brilliant scientist looking to fix her past mistakes, both professional and ethical, allies with Abbi, Juan and Tilda to track down the scientist responsible for their grim fates. Meanwhile, Dr. Alex Sarkov, a former child prodigy, refuses to let anyone or anything interfere with his goal of rewriting the human genome and ushering in the next stage of human evolution.",
         Genres : "Action - Adventure - Drama - Fantasy - Mystery - Sci-Fi",
         Release_date : "September 8, 2022 (United States)",
         Country_of_origin :  "Canada - United States",
      },
      {
         img : squid_game,
         title : "Squid Game",
         progress : "Finished", 
         max_season : "1 season",
         new_season : "SOON",
         progress_value : "100" ,
         storyline : "A story of people who fail at life for various reasons, but suddenly receive a mysterious invitation to participate in a survival game to win more than 38 million US dollars. The game takes place at an isolated island and the participants are locked up until there is a final winner. The story will incorporate popular children's games from the 1970s and 1980s of Korea, such as squid game, literal translation of its Korean name, which is a type of tag where offense and defense use a squid-shaped board drawn in the dirt.",
         Genres : "Action - Drama - Mystery - Thriller",
         Release_date : "September 17, 2021 (United States)",
         Country_of_origin :  "South Korea",
      },
      {
         img : locke_and_key,
         title : "Locke And Key",
         progress : "Finished", 
         max_season : "3 seasons",
         new_season : "NOPE",
         progress_value : "100" ,
         storyline : "After their father is murdered under mysterious circumstances, the three Locke siblings and their mother move into their ancestral home, Keyhouse, which they discover is full of magical keys that may be connected to their father's death. As the Locke children explore the different keys and their unique powers, a mysterious demon awakens - and will stop at nothing to steal them. From Carlton Cuse and Meredith Averill, Locke and Key is a coming-of-age mystery about love, loss, and the unshakable bonds that define family.",
         Genres : "Drama - Fantasy - Horror - Mystery - Thriller",
         Release_date : "February 7, 2020 (United States)",
         Country_of_origin :  "Canada - United States",
      },
      //Outer banks
];
export default CardTvShowData;